from fbchat import Client
from fbchat.models import *
import time

client = Client("email", "password")
thread_id = 'groupid'
thread_type = ThreadType.GROUP
client.sendRemoteImage('https://media.giphy.com/media/l3q2zVr6cu95nF6O4/giphy.gif', message=Message(text="IT'S PARTY TIME!"), thread_id=thread_id, thread_type=thread_type)
while True:
    client.changeThreadColor(ThreadColor.MESSENGER_BLUE, thread_id=thread_id)
    client.changeThreadEmoji('😡', thread_id=thread_id)
    time.sleep(0.1) 
    client.changeThreadColor(ThreadColor.BILOBA_FLOWER, thread_id=thread_id)
    client.changeThreadEmoji('😈', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.BRILLIANT_ROSE, thread_id=thread_id)
    client.changeThreadEmoji('😡', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.CAMEO, thread_id=thread_id)
    client.changeThreadEmoji('😈', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.DEEP_SKY_BLUE, thread_id=thread_id)
    client.changeThreadEmoji('😡', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.FERN, thread_id=thread_id)
    client.changeThreadEmoji('😈', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.FREE_SPEECH_GREEN, thread_id=thread_id)
    client.changeThreadEmoji('😡', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.GOLDEN_POPPY, thread_id=thread_id)
    client.changeThreadEmoji('😈', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.LIGHT_CORAL, thread_id=thread_id)
    client.changeThreadEmoji('😡', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.MEDIUM_SLATE_BLUE, thread_id=thread_id)
    client.changeThreadEmoji('😈', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.PICTON_BLUE, thread_id=thread_id)
    client.changeThreadEmoji('😡', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.PUMPKIN, thread_id=thread_id)
    client.changeThreadEmoji('😈', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.RADICAL_RED, thread_id=thread_id)
    client.changeThreadEmoji('😡', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.SHOCKING, thread_id=thread_id)
    client.changeThreadEmoji('😈', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadColor(ThreadColor.VIKING , thread_id=thread_id)
    client.changeThreadEmoji('😡', thread_id=thread_id)
    time.sleep(0.1)
    client.changeThreadEmoji('😈', thread_id=thread_id)